### PR TITLE
Port to tornado HTTPServer

### LINKED ISSUE #4: Broken with Tornado 6.0
`tornado.wsgi.WSGIApplication` was removed in Tornado 6.0 ([source](https://github.com/tornadoweb/tornado/releases/tag/v6.0.0))

Used in [_provide.py](https://github.com/altair-viz/altair_data_server/blob/04952648baaa2f643d037d8c501873d978df69e2/altair_data_server/_provide.py#L134)

### PR DESCRIPTION
**Pull request by crepererum**
This also makes altair_data_server compatible with Tornda 6.

Closes #4

### CODE REVIEW

**Comment by jakevdp** [comment]
Wow, this is really great – thanks for the contribution! I tried it without the proxy and it worked great, but I couldn't get it to work with the ``data_server_proxied`` endpoint on binder. Have you tried that?

**Comment by crepererum** [comment]
I'll double-check and let you know.

**Comment by crepererum** [comment]
Ah wait, does binder have the jupyter-server-proxy installed / set up?

**Comment by crepererum** [comment]
Ah OK, it isn't. But binder (luckily) only uses 1 virtualenv for both, the server and the kernel. So I've added a commit with a post-install script that installs the proxy and adjusted the demo notebook to use the proxied variant. This works in jupyterlabs if you downgrade altair to version 2.x (3.x only works with jupyterlabs 1.x which is hopefully going to be released in 3-4 days).

**Comment by jakevdp** [comment]
Ah, I see... I installed the proxy in the binder notebook and reset the runtime, but that didn't restart kernel manager.

**Comment by jakevdp** [comment]
Looks great, thanks for putting this together!

**Pull request merged**
